version: '3'

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./database:/docker-entrypoint-initdb.d
